import { Archetype } from '@/types';

export const ARCHETYPES: Archetype[] = [
  {
    id: 'passionate-heart', code: 'EDRS', name: 'Passionate Heart', emoji: '❤️',
    description: 'You love deeply, express emotions openly, and bring warmth and excitement into your relationships.',
    whatMakesYouUnique: 'You value emotional openness and believe that love should be felt and expressed clearly. You thrive in relationships where communication is honest and affection is freely shared. Your combination of emotional expressiveness, directness in conflict, romantic nature, and love of structure makes you a deeply intentional partner who builds lasting emotional intimacy.',
    strengths: ['Creates deep emotional intimacy', 'Communicates openly and honestly', 'Keeps romance alive with thoughtful gestures', 'Deeply invested in the relationship\'s growth'],
    growthAreas: ['May feel frustrated if partner is emotionally reserved', 'Emotional intensity may overwhelm quieter partners', 'May expect strong emotional connection too quickly'],
    whatYouNeedInPartner: ['Communicates honestly and openly', 'Appreciates romantic gestures and effort', 'Values emotional depth and vulnerability', 'Respects your emotional expressiveness'],
    compatibleWith: ['RDRS', 'EAPS', 'EARP'],
    color: '#E05C5C', gradientFrom: '#C94848', gradientTo: '#F07070',
  },
  {
    id: 'romantic-adventurer', code: 'EDRP', name: 'Romantic Adventurer', emoji: '🌹',
    description: 'You bring passion, honesty, and spontaneity to love. Every day with you feels like an adventure.',
    whatMakesYouUnique: 'You combine emotional openness with a love for spontaneity that keeps relationships exciting. You\'re not afraid to confront issues head-on, and you express love through grand romantic gestures and surprise experiences. Your energy is magnetic, and you bring a sense of wonder to everything you do together.',
    strengths: ['Keeps the relationship exciting and fresh', 'Openly expresses love and affection', 'Tackles problems directly with honesty', 'Creates memorable, spontaneous experiences'],
    growthAreas: ['May struggle with routine or predictability', 'Can be impulsive in emotional moments', 'Might overwhelm partners who prefer stability'],
    whatYouNeedInPartner: ['Enjoys adventure and spontaneous plans', 'Values open emotional expression', 'Can handle direct, honest conversations', 'Appreciates romance and creative gestures'],
    compatibleWith: ['RDRP', 'EARS', 'EDRS'],
    color: '#E8845A', gradientFrom: '#D47040', gradientTo: '#F09870',
  },
  {
    id: 'devoted-planner', code: 'EDPS', name: 'Devoted Planner', emoji: '📋',
    description: 'You show love through dedication, organization, and making sure everything runs smoothly for those you care about.',
    whatMakesYouUnique: 'You are the partner everyone wishes they had when life gets complicated. Your emotional expressiveness means your partner always knows where they stand, while your practical nature ensures love is shown through consistent, reliable action. You plan ahead, create stability, and build a future with intention.',
    strengths: ['Creates stability and security in relationships', 'Shows love through consistent, practical actions', 'Addresses issues head-on before they escalate', 'Plans thoughtfully for the future together'],
    growthAreas: ['May prioritize logistics over romance', 'Can come across as controlling when planning', 'Might struggle to be spontaneous or playful'],
    whatYouNeedInPartner: ['Appreciates structure and planning', 'Values emotional honesty and openness', 'Recognizes practical acts as expressions of love', 'Shares your vision for a stable future'],
    compatibleWith: ['RDPS', 'EAPS', 'EDRS'],
    color: '#5B8FD4', gradientFrom: '#4A7BBF', gradientTo: '#70A3E8',
  },
  {
    id: 'playful-partner', code: 'EDPP', name: 'Playful Partner', emoji: '🎉',
    description: 'You bring joy, honesty, and lightheartedness to love. Your partner never has to guess how you feel.',
    whatMakesYouUnique: 'You have a rare gift for making relationships feel both honest and fun. You tackle tough conversations with directness but keep the overall vibe light and playful. You show love through actions and adventures, and your spontaneous energy keeps things from ever feeling stale. With you, love is a joyful ride.',
    strengths: ['Brings levity and fun to the relationship', 'Communicates feelings directly and clearly', 'Shows love through thoughtful actions', 'Keeps things fresh with spontaneous energy'],
    growthAreas: ['May avoid serious depth in favor of fun', 'Can struggle with long-term planning', 'Might be seen as not taking things seriously enough'],
    whatYouNeedInPartner: ['Has a good sense of humor and playfulness', 'Values honesty and direct communication', 'Enjoys going with the flow', 'Appreciates love shown through actions'],
    compatibleWith: ['RDPP', 'EARP', 'EAPP'],
    color: '#F6B17A', gradientFrom: '#E09A62', gradientTo: '#F8C496',
  },
  {
    id: 'emotional-idealist', code: 'EARS', name: 'Emotional Idealist', emoji: '✨',
    description: 'You dream of a perfect love story and pour your heart into making it real. Deeply romantic and emotionally expressive.',
    whatMakesYouUnique: 'You feel everything deeply and believe in the transformative power of love. You wear your heart on your sleeve and create beautiful romantic moments. While you may avoid confrontation, your emotional depth and romantic vision make your relationships deeply meaningful. You see the best in your partner and inspire them to grow.',
    strengths: ['Creates a deeply romantic atmosphere', 'Emotionally generous and expressive', 'Sees and nurtures the best in their partner', 'Builds a stable, beautiful life together'],
    growthAreas: ['May avoid necessary confrontations', 'Can idealize the relationship unrealistically', 'Might suppress frustration until it builds up'],
    whatYouNeedInPartner: ['Approaches conflict gently and patiently', 'Values romance and emotional expression', 'Creates a safe space for vulnerability', 'Appreciates your idealistic vision of love'],
    compatibleWith: ['RDRS', 'EDRP', 'RARS'],
    color: '#9B72CF', gradientFrom: '#8560BB', gradientTo: '#AF86E0',
  },
  {
    id: 'dreamy-romantic', code: 'EARP', name: 'Dreamy Romantic', emoji: '🌙',
    description: 'You live for spontaneous love, emotional expression, and the magic of unexpected moments together.',
    whatMakesYouUnique: 'You are the embodiment of free-spirited love. Emotionally open, deeply romantic, and spontaneous by nature, you create a relationship that feels like a movie. You express your feelings freely and believe love should be an adventure. Your warmth and imagination make every moment together feel special.',
    strengths: ['Creates magical, spontaneous moments', 'Expresses emotions freely and beautifully', 'Keeps romance alive naturally', 'Brings warmth and imagination to love'],
    growthAreas: ['May struggle with practical responsibilities', 'Can avoid difficult conversations too long', 'Might feel trapped by routine or structure'],
    whatYouNeedInPartner: ['Loves spontaneity and surprise', 'Values emotional openness and vulnerability', 'Creates space for romantic expression', 'Is patient with conflict-avoidant tendencies'],
    compatibleWith: ['RARP', 'EDRS', 'EDPP'],
    color: '#7B8FA6', gradientFrom: '#647892', gradientTo: '#8FA3BA',
  },
  {
    id: 'gentle-supporter', code: 'EAPS', name: 'Gentle Supporter', emoji: '🤲',
    description: 'You show love through steady presence, emotional warmth, and practical care. A true safe harbor.',
    whatMakesYouUnique: 'You combine emotional openness with practical, structured love. While you prefer harmony over confrontation, you express care through both words and actions. Your partner always knows you\'re there for them, and your consistent, organized approach to life creates a foundation of security and trust.',
    strengths: ['Creates emotional safety and warmth', 'Shows love through consistent care', 'Brings stability and organization to the relationship', 'Expresses feelings openly and genuinely'],
    growthAreas: ['May avoid addressing problems directly', 'Can become a caretaker at the expense of own needs', 'Might struggle to set firm boundaries'],
    whatYouNeedInPartner: ['Handles conflict gently and respectfully', 'Values practical expressions of love', 'Appreciates emotional warmth and openness', 'Supports a structured, stable lifestyle'],
    compatibleWith: ['EDPS', 'RDPS', 'EDRS'],
    color: '#4CAF9A', gradientFrom: '#3D9B84', gradientTo: '#5DC4AA',
  },
  {
    id: 'cheerful-companion', code: 'EAPP', name: 'Cheerful Companion', emoji: '☀️',
    description: 'You light up every room with your warmth, positivity, and ability to make love feel effortless.',
    whatMakesYouUnique: 'You bring sunshine to your relationships. Emotionally expressive and naturally positive, you show love through both heartfelt words and practical support. Your spontaneous nature means there\'s never a dull moment, and your preference for harmony means your partner always feels at ease. You make love look easy.',
    strengths: ['Brings positivity and joy to the relationship', 'Makes partner feel emotionally understood', 'Flexible and easygoing in daily life', 'Shows love through both words and actions'],
    growthAreas: ['May use positivity to avoid deeper issues', 'Can struggle with long-term planning', 'Might need to address conflicts more directly'],
    whatYouNeedInPartner: ['Matches your positive, easygoing energy', 'Values emotional expression and warmth', 'Enjoys spontaneity and flexibility', 'Can gently help navigate difficult conversations'],
    compatibleWith: ['EDPP', 'RAPP', 'EARP'],
    color: '#F0C75E', gradientFrom: '#D9B248', gradientTo: '#F5D878',
  },
  {
    id: 'emotional-sage', code: 'RDRS', name: 'Emotional Sage', emoji: '🌿',
    description: 'Calm, wise, and deeply romantic beneath a composed exterior. You love with quiet intensity and thoughtful devotion.',
    whatMakesYouUnique: 'You possess a rare combination of inner calm and romantic depth. While you may not wear your emotions on your sleeve, your love is shown through deeply intentional romantic gestures and honest communication. When issues arise, you address them directly but thoughtfully. Your structured approach to life creates a stable foundation for lasting love.',
    strengths: ['Brings calm wisdom to emotional situations', 'Communicates directly when it matters', 'Expresses love through intentional romantic gestures', 'Creates a stable, secure relationship environment'],
    growthAreas: ['May seem emotionally distant at times', 'Can over-think emotions instead of feeling them', 'Partner may wish for more spontaneous expression'],
    whatYouNeedInPartner: ['Respects your quieter emotional style', 'Values honest, direct communication', 'Appreciates thoughtful romantic gestures', 'Supports a structured, planned lifestyle'],
    compatibleWith: ['EDRS', 'EARS', 'RDPS'],
    color: '#4CAF9A', gradientFrom: '#3D9B84', gradientTo: '#5DC4AA',
  },
  {
    id: 'quiet-strategist', code: 'RDRP', name: 'Quiet Strategist', emoji: '🎯',
    description: 'You approach love with thoughtful precision and romantic flair, combined with a love for adventure.',
    whatMakesYouUnique: 'You are the quiet mastermind of romance. Reserved on the surface, you express love through carefully planned romantic surprises and spontaneous getaways. You handle conflict head-on but with measured calm, and your ability to read situations deeply makes you an incredibly perceptive partner. Life with you is a well-crafted adventure.',
    strengths: ['Deeply perceptive and thoughtful', 'Balances romance with spontaneous excitement', 'Handles conflict calmly and directly', 'Creates meaningful, well-planned surprises'],
    growthAreas: ['May keep emotions too guarded initially', 'Can overthink spontaneous moments', 'Partner may struggle to read your emotional state'],
    whatYouNeedInPartner: ['Is patient with your reserved emotional style', 'Enjoys romantic gestures and surprises', 'Values spontaneity and flexibility', 'Appreciates direct, calm communication'],
    compatibleWith: ['EDRP', 'RARS', 'RDRS'],
    color: '#7B8FA6', gradientFrom: '#647892', gradientTo: '#8FA3BA',
  },
  {
    id: 'loyal-anchor', code: 'RDPS', name: 'Loyal Anchor', emoji: '⚓',
    description: 'Dependable, practical, and direct. You build relationships that last through consistency and honest communication.',
    whatMakesYouUnique: 'You are the rock every relationship needs. Your reserved nature means you show love through actions rather than words, and your practical approach ensures your partner always feels taken care of. You don\'t shy away from tough conversations, and your structured lifestyle creates the stability that makes deep love possible.',
    strengths: ['Extremely dependable and reliable', 'Shows love through consistent practical actions', 'Addresses issues directly and honestly', 'Builds long-term stability and security'],
    growthAreas: ['May struggle to express emotions verbally', 'Can seem unromantic or too practical', 'Might prioritize duty over emotional connection'],
    whatYouNeedInPartner: ['Recognizes actions as expressions of love', 'Values stability and reliability', 'Appreciates direct, honest communication', 'Is patient with reserved emotional expression'],
    compatibleWith: ['EAPS', 'EDPS', 'RDRS'],
    color: '#5B8FD4', gradientFrom: '#4A7BBF', gradientTo: '#70A3E8',
  },
  {
    id: 'independent-explorer', code: 'RDPP', name: 'Independent Explorer', emoji: '🧭',
    description: 'You value freedom, honesty, and practical love. A self-sufficient partner who keeps things real.',
    whatMakesYouUnique: 'You bring a refreshing honesty and independence to relationships. Reserved emotionally but direct when it counts, you show love through practical support and shared adventures. Your spontaneous nature keeps things exciting, and your self-sufficiency means you bring a healthy, whole self to the partnership.',
    strengths: ['Brings healthy independence to the relationship', 'Honest and direct about needs and feelings', 'Shows love through practical support and actions', 'Keeps things exciting with spontaneous energy'],
    growthAreas: ['May seem emotionally unavailable at times', 'Can prioritize independence over togetherness', 'Might struggle with emotional vulnerability'],
    whatYouNeedInPartner: ['Respects your need for independence', 'Values honesty and directness', 'Enjoys spontaneous adventures', 'Doesn\'t require constant emotional expression'],
    compatibleWith: ['EDPP', 'EAPP', 'RDRP'],
    color: '#E8845A', gradientFrom: '#D47040', gradientTo: '#F09870',
  },
  {
    id: 'quiet-romantic', code: 'RARS', name: 'Quiet Romantic', emoji: '🕯️',
    description: 'A gentle soul with a deeply romantic heart. You love quietly but profoundly.',
    whatMakesYouUnique: 'You are the still water that runs deep. Behind your reserved exterior lies a deeply romantic heart that expresses love through beautiful, thoughtful gestures. You prefer harmony and avoid conflict, creating a peaceful relationship environment. Your structured approach means your love is consistent and reliable, even if it\'s expressed quietly.',
    strengths: ['Creates a peaceful, harmonious relationship', 'Expresses love through thoughtful romantic gestures', 'Deeply loyal and consistent', 'Brings quiet stability and warmth'],
    growthAreas: ['May avoid important conversations too long', 'Can struggle to express needs directly', 'Might internalize frustration silently'],
    whatYouNeedInPartner: ['Creates a safe space for quiet expression', 'Values peace and harmony in the relationship', 'Appreciates subtle romantic gestures', 'Can initiate difficult conversations gently'],
    compatibleWith: ['EARS', 'RDRS', 'RARP'],
    color: '#9B72CF', gradientFrom: '#8560BB', gradientTo: '#AF86E0',
  },
  {
    id: 'thoughtful-dreamer', code: 'RARP', name: 'Thoughtful Dreamer', emoji: '💭',
    description: 'You live in a world of quiet romance and spontaneous beauty. Love, for you, is a gentle adventure.',
    whatMakesYouUnique: 'You bring a unique magic to relationships with your combination of quiet depth and spontaneous romanticism. You express love through unexpected romantic gestures and dreamy experiences. While you prefer to avoid conflict, your inner world is rich and your love is deeply felt. With you, life is poetry in motion.',
    strengths: ['Creates unexpectedly beautiful moments', 'Brings depth and meaning to the relationship', 'Flexible and adaptable in daily life', 'Loves with quiet but genuine intensity'],
    growthAreas: ['May struggle to communicate needs clearly', 'Can withdraw from practical responsibilities', 'Might avoid addressing relationship issues'],
    whatYouNeedInPartner: ['Appreciates your quiet, romantic nature', 'Enjoys spontaneous experiences together', 'Can gently bring up difficult topics', 'Values depth over surface-level connection'],
    compatibleWith: ['EARP', 'RARS', 'EARS'],
    color: '#8DB5C8', gradientFrom: '#76A0B5', gradientTo: '#A4CCDC',
  },
  {
    id: 'steady-supporter', code: 'RAPS', name: 'Steady Supporter', emoji: '🛡️',
    description: 'You are the quiet strength behind every great relationship. Practical, steady, and deeply caring.',
    whatMakesYouUnique: 'You are the unsung hero of love. Reserved in expression but boundless in care, you show love through consistent practical support and a structured, stable life. You prefer peace over confrontation and demonstrate devotion through reliability. Your partner can always count on you, even when you don\'t say much.',
    strengths: ['Extremely reliable and trustworthy', 'Shows love through consistent daily actions', 'Creates a stable, secure home environment', 'Calm and steady in challenging times'],
    growthAreas: ['May seem emotionally unavailable or distant', 'Can avoid addressing problems until too late', 'Might struggle to express affection verbally'],
    whatYouNeedInPartner: ['Recognizes and values practical expressions of love', 'Is patient with reserved emotional expression', 'Values stability and routine', 'Can initiate emotional conversations gently'],
    compatibleWith: ['EAPS', 'EDPS', 'RARS'],
    color: '#7077A1', gradientFrom: '#5D648E', gradientTo: '#848AB6',
  },
  {
    id: 'easygoing-observer', code: 'RAPP', name: 'Easygoing Observer', emoji: '🍃',
    description: 'Relaxed, practical, and quietly perceptive. You love by being present and going with the flow.',
    whatMakesYouUnique: 'You bring a rare sense of calm acceptance to relationships. Reserved but observant, you notice the little things and show care through practical, spontaneous acts. You don\'t need grand gestures or intense conversations to feel connected. Your easygoing nature and flexibility make you the ideal partner for someone who values peace and genuine presence.',
    strengths: ['Creates a relaxed, pressure-free environment', 'Deeply observant and perceptive of partner\'s needs', 'Flexible and adaptable to any situation', 'Shows love through quiet, practical acts'],
    growthAreas: ['May seem too detached or uninvested', 'Can avoid confrontation even when necessary', 'Might struggle with structured planning'],
    whatYouNeedInPartner: ['Appreciates your calm, easygoing nature', 'Doesn\'t demand constant emotional expression', 'Enjoys going with the flow', 'Can gently initiate important conversations'],
    compatibleWith: ['EAPP', 'RDPP', 'RARP'],
    color: '#F0C75E', gradientFrom: '#D9B248', gradientTo: '#F5D878',
  },
];

export function getArchetypeByCode(code: string): Archetype | undefined {
  return ARCHETYPES.find((a) => a.code === code);
}

export function getArchetypeById(id: string): Archetype | undefined {
  return ARCHETYPES.find((a) => a.id === id);
}
